class PostNotFoundException(message: String) : Exception(message)
class UserNotFoundException(message: String) : Exception(message)
class CommentNotFoundException(message: String) : Exception(message)
class KeyNotFoundException(message: String) : Exception(message)
class NoteNotFoundException(message: String) : Exception(message)